[dr]
type = drive                                                                     
scope = drive
token = {"access_token":"ya29.a0AQvPyINYAD5jnUfxRZXN_sbqduGjQhE99mxCL4EMniRw6hoojWW9C85UDgUGWGRkv48XMW8sU0CByeUjrVuKy2PbEQoyCbIjlk8xMlJANiHwx2GTzjneDmkaXwPaM2vjqxqajEvPwVLQ7F4ACy5VPvdoLjSXCqtcfDymkC9msU82CLI9f_LqmF9yEcKhyc9Kc3LAmpMaCgYKAXMSARISFQHGX2MiE3P2quLldPh-LKkxcP5anQ0206","token_type":"Bearer","refresh_token":"1//0gCSpKVXucYEXCgYIARAAGBASNwF-L9IrAtoNgqPXagpxUAhBzC37mh8clVrzq7sATYyCwExeYwy1Qla8YXvf9H7PfcE6iguwBB0","expiry":"2026-05-09T07:25:59.017867455Z","expires_in":3599}
team_drive =
