#!/bin/bash
colornow=$(cat /etc/rmbl/theme/color.conf)
export NC="\e[0m"
export COLOR1="$(cat /etc/rmbl/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
export COLBG1="$(cat /etc/rmbl/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
ipsaya=$(curl -4 -s ifconfig.me/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/bheghenkz/premium/main/seler"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -- "$ipsaya" | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
  CHATID=$(cat /etc/per/id)
  KEY=$(cat /etc/per/token)
  URL="https://api.telegram.org/bot$KEY/sendMessage"
  TIMES="10"
TEXT="
<code>🧿───────────────────🧿</code>
<b>HANYA TERSEDIA UNTUK ADMIN VVIP</b>
<code>🧿───────────────────🧿</code>
<code>Please Buy Permission In Your Admin</code>
<code>ADMIN CONTACT</code>
<code>Telegram: <code></code>t.me/fensmilebots</code>
<code>Whatsapp: <code></code>wa.me/6289517087090</code>
<code>🧿───────────────────🧿</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
 clear
 exit
 fi
}
checking_sc
clear
Repo1="https://raw.githubusercontent.com/bheghenkz/premium/main/"
export MYIP=$( curl -4 -s ifconfig.me/ip )
SELLER=$(curl -sS ${Repo1}ip | grep -- "$MYIP" | awk '{print $2}')
Exp100=$(curl -sS ${Repo1}ip | grep -- "$MYIP" | awk '{print $3}')
data_ip="https://raw.githubusercontent.com/bheghenkz/premium/main/seler"
d2=$(date -d "$date_list" +"+%s")
d1=$(date -d "$Exp" +"+%s")
dayleft=$(( ($d1 - $d2) / 86400 ))

#########################
[[ ! -f /usr/bin/git ]] && apt install git -y &> /dev/null
# COLOR VALIDATION
clear
RED='\033[0;31m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
END='\e[0m'
AKTIF="VERIFIED"
TOKEN=$(cat /etc/github/api)
REPO="https://github.com/bheghenkz/premium.git"
EMAIL="fendysupratno@gmail.com"
USER="bheghenkz"
# linkinstal= https://justpaste.it/edit/62611736/yu5zlvfdabupd00t



add-ip() {
TOKEN=$(cat /etc/github/api)
REPO="https://github.com/bheghenkz/premium.git"
EMAIL="fendysupratno@gmail.com"
USER="bheghenkz"
TIMES="10"
CHATID=$(cat /etc/per/id)
KEY=$(cat /etc/per/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
DATELOG=`date +'%Y-%m-%d-%H-%M-%S'`
LOG="/tmp/${DATELOG}.txt"

    today=`date -d "0 days" +"%Y-%m-%d"`
    git clone ${REPO} /usr/local/sbin/premium/ &> /dev/null
    clear
    echo -e "$COLOR1╭═════════════════════════════════════════════════╮${NC}"
    echo -e "$COLOR1│${NC}${COLBG1}                 ${WH}INPUT IP ADDRESS                ${NC}$COLOR1│ $NC"
    echo -e "$COLOR1╰═════════════════════════════════════════════════╯${NC}"
    read -p " [INPUT IP] : " ip
    CLIENT_EXISTS=$(grep -w $ip /usr/local/sbin/premium/ip | wc -l)
    if [[ ${CLIENT_EXISTS} == '1' ]]; then
    echo "IP Already Exist !"
    rm -rf /usr/local/sbin/premium
    exit 0
    fi
    echo -e "$COLOR1╭═════════════════════════════════════════════════╮${NC}"
    echo -e "$COLOR1│${NC}${COLBG1}                 ${WH}INPUT USERNAME                   ${NC}$COLOR1│ $NC"
    echo -e "$COLOR1╰═════════════════════════════════════════════════╯${NC}"
    read -p " [TANPA SPASI]: " name
    clear
    echo -e "$COLOR1╭═════════════════════════════════════════════════╮${NC}"
    echo -e "$COLOR1│${NC}${COLBG1}           ${WH}• REGRISTRASI IP VPS •                ${NC}$COLOR1│ $NC"
    echo -e "$COLOR1╰═════════════════════════════════════════════════╯${NC}"
    echo -e "$COLOR1╭═════════════════════════════════════════════════╮${NC}"
    echo " [1] 30 Days"
    echo " [2] 60 Days"
    echo " [3] 90 Days"
    echo " [4] Lifetime"
    echo " [5] Custom Expiration Date"
    echo -e "$COLOR1╰═════════════════════════════════════════════════╯${NC}"
    read -p " [Input Number] : " exp
    
    if [[ ${exp} == '1' ]]; then
    exp2=`date -d "30 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /usr/local/sbin/premium/ip
    elif [[ ${exp} == '2' ]]; then
    exp2=`date -d "60 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /usr/local/sbin/premium/ip
    elif [[ ${exp} == '3' ]]; then
    exp2=`date -d "90 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /usr/local/sbin/premium/ip
    elif [[ ${exp} == '4' ]]; then
    exp2="Lifetime"
    echo "### ${name} ${exp2} ${ip}" >> /usr/local/sbin/premium/ip
    elif [[ ${exp} == '5' ]]; then
    read -p "Input Expired Days : " exp11
    exp2=`date -d "$exp11 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /usr/local/sbin/premium/ip
    fi
    sleep 2
    cd /usr/local/sbin/premium
    sudo git config --global user.email "fendysupratno@gmail.com" >> ${LOG} 2>&1
    sudo git config --global user.name "bheghenkz" >> ${LOG} 2>&1
    sudo rm -rf .git >> ${LOG} 2>&1
    sudo git init >> ${LOG} 2>&1
    sudo git add . >> ${LOG} 2>&1
    sudo git commit -m m >> ${LOG} 2>&1
    sudo git branch -M main >> ${LOG} 2>&1
    sudo git remote add origin https://github.com/bheghenkz/premium  >> ${LOG} 2>&1
    sudo git push -f https://REPLACE_WITH_YOUR_GITHUB_TOKEN@github.com/bheghenkz/premium.git >> ${LOG} 2>&1
    rm -rf /usr/local/sbin/premium
    clear
TEXT="
<code>🧿───────────────────🧿</code>
<b> REGRIST AUTOSCRIPT PREMIUM</b>
<code>🧿───────────────────🧿</code>
<code>ID   : </code><code>$name</code>
<code>Ip   : </code><code>$ip</code>
<code>Time : </code><code>$today</code>
<code>Exp  : </code><code>$exp2</code>
<code>🧿───────────────────🧿</code>
<i>Automatic Notification from Github</i>
<code>🧿───────────────────🧿</code>
<b>Klik To Create Link Instalaion</b>
https://justpaste.it/fekc0
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

del-ip() {
CHATID=$(cat /etc/per/id)
KEY=$(cat /etc/per/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
REPO="https://github.com/bheghenkz/premium.git"
DATELOG=`date +'%Y-%m-%d-%H-%M-%S'`
LOG="/tmp/${DATELOG}.txt"
TIMES="10"

    rm -rf /usr/local/sbin/premium
    git clone ${REPO} /usr/local/sbin/premium/ &> /dev/null
    clear
    echo ""
    echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "          \e[1;97mList IP Address Have Been Registered${NC}"
    echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    grep -E "^###"    "/usr/local/sbin/premium/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    grep -E "^#&"    "/usr/local/sbin/premium/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    echo ""
    echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

    read -p "   Input IP Address To Delete : " ipdel
    name=$(cat /usr/local/sbin/premium/ip | grep -- "$ipdel" | awk '{print $2}')
    exp=$(cat /usr/local/sbin/premium/ip | grep -- "$ipdel" | awk '{print $3}')
    sleep 1
    if [[ ${exp} == 'Lifetime' ]]; then
    sed -i "/^#&   $name   $exp $ipdel/,/^},{/d" /usr/local/sbin/premium/ip
    else
    sed -i "/^### $name $exp $ipdel/,/^},{/d" /usr/local/sbin/premium/ip
    fi
    sleep 2
    cd /usr/local/sbin/premium
    sudo git config --global user.email "fendysupratno@gmail.com" >> ${LOG} 2>&1
    sudo git config --global user.name "bheghenkz" >> ${LOG} 2>&1
    sudo rm -rf .git >> ${LOG} 2>&1
    sudo git init >> ${LOG} 2>&1
    sudo git add . >> ${LOG} 2>&1
    sudo git commit -m m >> ${LOG} 2>&1
    sudo git branch -M main >> ${LOG} 2>&1
    sudo git remote add origin https://github.com/bheghenkz/premium  >> ${LOG} 2>&1
    sudo git push -f https://REPLACE_WITH_YOUR_GITHUB_TOKEN@github.com/bheghenkz/premium.git >> ${LOG} 2>&1
    rm -rf /usr/local/sbin/premium
    clear
TEXT="
<code>🧿───────────────────🧿</code>
<b> DELETE IP AUTOSCRIPT PREMIUM</b>
<code>🧿───────────────────🧿</code>
<code>ID   : </code><code>$name</code>
<code>Ip   : </code><code>$ipdel</code>
<code>Exp  : </code><code>$exp</code>
<code>🧿───────────────────🧿</code>
<i>Automatic Notification from Github</i>
<code>🧿───────────────────🧿</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

renew-ip() {
CHATID=$(cat /etc/per/id)
KEY=$(cat /etc/per/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
REPO="https://github.com/bheghenkz/premium.git"
DATELOG=`date +'%Y-%m-%d-%H-%M-%S'`
LOG="/tmp/${DATELOG}.txt"
TIMES="10"

    rm -rf /usr/local/sbin/premium
    git clone ${REPO} /usr/local/sbin/premium/ &> /dev/null
    clear
    echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "          \e[1;97mList IP Address Have Been Registered${NC}"
    echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    grep -E "^###" "/root/ipvps/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    echo ""
    echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    read -p "  Input IP Address To Renew : " ipdel
    read -p "  Input Days  : " days
    name=$(cat /usr/local/sbin/premium/ip | grep -- "$ipdel" | awk '{print $2}')
    exp=$(cat /usr/local/sbin/premium/ip | grep -- "$ipdel" | awk '{print $3}')
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $days))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "s/### $name $exp $ipdel/### $name $exp4 $ipdel/g" /usr/local/sbin/premium/ip
    sleep 2
    cd /usr/local/sbin/premium
    sudo git config --global user.email "fendysupratno@gmail.com" >> ${LOG} 2>&1
    sudo git config --global user.name "bheghenkz" >> ${LOG} 2>&1
    sudo rm -rf .git >> ${LOG} 2>&1
    sudo git init >> ${LOG} 2>&1
    sudo git add . >> ${LOG} 2>&1
    sudo git commit -m m >> ${LOG} 2>&1
    sudo git branch -M main >> ${LOG} 2>&1
    sudo git remote add origin https://github.com/bheghenkz/premium  >> ${LOG} 2>&1
    sudo git push -f https://REPLACE_WITH_YOUR_GITHUB_TOKEN@github.com/bheghenkz/premium.git >> ${LOG} 2>&1
    rm -rf /usr/local/sbin/premium
    clear
TEXT="
<code>🧿───────────────────🧿</code>
<b> RENEW IP AUTOSCRIPT PREMIUM</b>
<code>🧿───────────────────🧿</code>
<code>ID   : </code><code>$name</code>
<code>Ip   : </code><code>$ipdel</code>
<code>Exp  : </code><code>$exp4</code>
<code>🧿───────────────────🧿</code>
<i>Automatic Notification from Github</i>
<code>🧿───────────────────🧿</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

clear

echo -e "$COLOR1╭═════════════════════════════════════════════════╮${NC}"
echo -e "$COLOR1│${NC}${COLBG1}           ${WH}• REGRISTRASI IP VPS •                ${NC}$COLOR1│ $NC"
echo -e "$COLOR1╰═════════════════════════════════════════════════╯${NC}"
echo -e "$COLOR1╭═════════════════════════════════════════════════╮${NC}"
echo -e " ${grenbo}[1]$NC  ${YELL}Add IP VPS"$NC     
echo -e " ${grenbo}[2]$NC  ${YELL}Delete IP VPS"$NC
echo -e " ${grenbo}[3]$NC  ${YELL}Renew IP VPS"$NC
echo -e " ${grenbo}[4]$NC  ${YELL}EXIT ADD IP"$NC
echo -e "$COLOR1╰═════════════════════════════════════════════════╯${NC}"
read -p "[Input Number] : " menu
case $menu in
1 | 01)
clear
add-ip
;;
2 | 02)
clear
del-ip
;;
3 | 03)
clear
renew-ip
;;

4 | 04)
clear
menu
;;

*)
echo "Please Input An Correct Menu !"
sleep 1
clear
menu
;;
esac